// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR_pFpD3xi7pbqWz2BP5d1VZEweMclBtM',
    appId: '1:129877128933:web:2aaf8be801d9c28ccf060c',
    messagingSenderId: '129877128933',
    projectId: 'obonstore-5b8cf',
    authDomain: 'obonstore-5b8cf.firebaseapp.com',
    storageBucket: 'obonstore-5b8cf.appspot.com',
    measurementId: 'G-JJ9DQQH4RM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwTOlJRJcjD2xVpP9rlftKh4uFU3WFkGc',
    appId: '1:129877128933:android:0952689c7430355ccf060c',
    messagingSenderId: '129877128933',
    projectId: 'obonstore-5b8cf',
    storageBucket: 'obonstore-5b8cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpk4sWSgIIRGwxZLlgltNVgZg3Djbkes4',
    appId: '1:129877128933:ios:b9b41676973220f0cf060c',
    messagingSenderId: '129877128933',
    projectId: 'obonstore-5b8cf',
    storageBucket: 'obonstore-5b8cf.appspot.com',
    iosClientId: '129877128933-qjpom7nv9748e4o21dpet451tkj0q5pk.apps.googleusercontent.com',
    iosBundleId: 'com.obon.obonstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpk4sWSgIIRGwxZLlgltNVgZg3Djbkes4',
    appId: '1:129877128933:ios:48d380b9d8af46e3cf060c',
    messagingSenderId: '129877128933',
    projectId: 'obonstore-5b8cf',
    storageBucket: 'obonstore-5b8cf.appspot.com',
    iosClientId: '129877128933-q56j3seefrk40jrjv3enm0d6r6lfh198.apps.googleusercontent.com',
    iosBundleId: 'com.example.obonstore.RunnerTests',
  );
}
